//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModCompDBEntities : DbContext
    {
        public ModCompDBEntities()
            : base("name=ModCompDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Experiment> Experiment { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Scene> Scene { get; set; }
        public virtual DbSet<Sprav_Acva> Sprav_Acva { get; set; }
        public virtual DbSet<Sprav_GAS> Sprav_GAS { get; set; }
        public virtual DbSet<Sprav_Objects> Sprav_Objects { get; set; }
        public virtual DbSet<Step_Model> Step_Model { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
