//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int Id_mod { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Autor { get; set; }
        public string Designer { get; set; }
        public Nullable<System.DateTime> DateUp { get; set; }
        public string Descr { get; set; }
        public string Path_FullDescr { get; set; }
        public string Path_Exec { get; set; }
    }
}
