//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scene
    {
        public int Id_sc { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_exp { get; set; }
        public Nullable<int> Id_acvatorii { get; set; }
        public Nullable<System.DateTime> DataReg { get; set; }
        public string Descr { get; set; }
    }
}
