//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprav_Acva
    {
        public int Id_acv { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public string Descr { get; set; }
    }
}
