//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprav_Objects
    {
        public int Id_obj { get; set; }
        public string Symbol_id { get; set; }
        public string Class_obj { get; set; }
        public string Vid_obj { get; set; }
        public string Type_obj { get; set; }
        public string Descr { get; set; }
    }
}
