//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprav_GAS
    {
        public int Id_GAS { get; set; }
        public string Type { get; set; }
        public string Ent_num { get; set; }
        public Nullable<float> Coord_X { get; set; }
        public Nullable<float> Coord_Y { get; set; }
        public Nullable<float> Coord_Z { get; set; }
        public Nullable<float> Lat { get; set; }
        public Nullable<float> Long { get; set; }
        public Nullable<float> Depth { get; set; }
    }
}
