//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step_Model
    {
        public int Id_step { get; set; }
        public Nullable<int> Id_exp { get; set; }
        public Nullable<int> Id_scene { get; set; }
        public string Type_mod { get; set; }
        public string Name { get; set; }
        public string Path_exe { get; set; }
        public Nullable<System.DateTime> Startt { get; set; }
        public Nullable<System.DateTime> Endt { get; set; }
        public string Descr { get; set; }
    }
}
